# Site settings
title: Axelerant Developer Handbook
email:
description:
baseurl: ""
url: "https://axelerant.github.io"
twitter_username: axelerant
github_username: axelerant
host: 0.0.0.0

# Build settings
markdown: kramdown

# Contrib gems
gems:
  - jekyll-sitemap

toc:
  - General
  - Front-end
  - Back-end
  - Devops
